version: "2"

linters:
  disable-all: true
  enable:
    # --- Correctness & Safety ---
    - govet
    - staticcheck
    - errcheck
    - bodyclose
    - copyloopvar
    - noctx
    - contextcheck
    - exhaustive
    - gosec

    # --- Code Quality ---
    - unused
    - ineffassign
    - unconvert
    - prealloc
    - errchkjson
    - durationcheck

    # --- Style & Consistency ---
    - revive
    - misspell
    - whitespace
    - tagliatelle
    - gocritic

    # --- Complexity & Functions ---
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - goconst

    # --- Architecture & Discipline ---
    - depguard
    - forbidigo
    - nolintlint

linters-settings:
  funlen:
    lines: 80
    statements: 40
    # Максимум аргументов (костыль через revive / funlen)
    max-args: 5

  gocyclo:
    min-complexity: 12

  gocognit:
    min-complexity: 12

  nestif:
    min-complexity: 3

  goconst:
    min-len: 2
    min-occurrences: 2

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: false
      - name: error-strings
        severity: error
      - name: error-naming
        severity: error
      - name: error-return
        severity: error
      - name: dot-imports
        severity: error
      - name: import-blacklist
        arguments:
          - internal/cmd
          - internal/adapters/mysql
          - internal/adapters/http
        severity: error
        comment: "Core can only depend on interfaces, not concrete implementations"
      - name: switch-case-count
        arguments:
          max: 3
          comment: "TODO: consider map+func or strategy pattern for many cases"
      - name: package-level-vars
        severity: error
        comment: "Avoid global state in core packages"

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
    disabled-checks:
      - whyNoLint

  nolintlint:
    require-specific: true
    require-explanation: true

  gosec:
    severity: high
    confidence: medium
    excludes:
      - G104

  depguard:
    list-type: blacklist
    packages:
      internal/adapters/mysql: "Core package must not import storage directly"
      internal/cmd: "Core package must not import CLI code"

  forbidigo:
    forbid:
      fmt.Println: "Use structured logger interface instead (e.g., slog)"
      panic: "Do not panic in core package; return error instead"
      os.Exit: "Do not exit from core package; propagate error to main"
      var _: "Do not declare package-level state in core packages; use dependency injection"


issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - contextcheck
        - funlen
        - gocyclo
        - gocognit

run:
  timeout: 3m
  tests: true
