version: "2"

linters:
  default: none
  enable:
    - fileprefix

  settings:
    custom:
      fileprefix:
        type: module
        description: Disallow filenames that start with the package name
        settings:
          message: "filename contains package name; consider extracting the logic into a separate package"
          excludeDirs:
            - telegram
