version: "2"

linters:
  disable-all: true
  enable:
    # --- 1. Correctness & Safety (BASE) ---
    - govet
    - staticcheck
    - errcheck
    - nilerr
    - bodyclose
    - copyloopvar
    - contextcheck
    - gosec

    # --- 2. Code Quality ---
    - unused
    - ineffassign
    - unconvert
    - prealloc
    - durationcheck

    # --- 3. Style & Consistency ---
    - revive
    - misspell
    - whitespace
    - gocritic
    - tagliatelle

    # --- 4. Complexity (REAL LIMITS) ---
    - gocyclo
    - gocognit
    - funlen
    - goconst

    # --- 5. Discipline ---
    - nolintlint

linters-settings:
  # ---- Complexity ----
  funlen:
    lines: 80
    statements: 40

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  # ---- Style ----
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: true

      - name: error-strings
        severity: error
      - name: error-naming
        severity: error
      - name: error-return
        severity: error
      - name: dot-imports
        severity: error

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult

  tagliatelle:
    case:
      rules:
        json: snake

  nolintlint:
    require-specific: true
    require-explanation: true

  gosec:
    severity: high
    confidence: medium
    excludes:
      - G104

issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - contextcheck
        - funlen
        - gocyclo
        - gocognit

run:
  timeout: 3m
  tests: true
