version: "2"

linters:
  enable:
    # --- Correctness & Safety ---
    - govet
    - staticcheck
    - errcheck
    - bodyclose
    - copyloopvar
    - noctx
    - contextcheck
    - exhaustive
    - gosec

    # --- Code Quality ---
    - unused
    - ineffassign
    - unconvert
    - prealloc
    - errchkjson
    - durationcheck
    - dupl

    # --- Style & Consistency ---
    - revive
    - misspell
    - whitespace
    - tagliatelle
    - gocritic
    - lll

    # --- Complexity & Functions ---
    - gocyclo
    - gocognit
    - funlen
    - maintidx
    - nestif
    - goconst

    # --- Architecture & Discipline ---
    # depguard disabled - not suitable for CLI tools
    - nolintlint

linters-settings:
  funlen:
    lines: 50
    statements: 30
    max-args: 5

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental      # NEW: экспериментальные проверки
    enabled-checks:
      - all                 # Включает все доступные проверки

  gocyclo:
    # Cyclomatic complexity threshold (22 for type switches)
    min-complexity: 22

  gocognit:
    # Cognitive complexity threshold (25 for type switches)
    min-complexity: 25

  nestif:
    min-complexity: 3

  goconst:
    min-len: 2
    min-occurrences: 2

  maintidx:
    under: 20

  lll:
    # Максимальная длина строки
    line-length: 120
    # Пропускать строки с тегами
    tab-width: 2

  # NEW: Находим дублирование кода
  dupl:
    threshold: 100

  # Exclude external API JSON tags from tagliatelle
  tagliatelle:
    excluded:
      - display_name  # External API format (Nominatim)

  revive:
    rules:
      - name: file-length-limit
        severity: error
        arguments: [{max: 199, skipBlankLines: true, skipComments: true}]
      - name: exported
        severity: warning
        # NEW: проверять что публичные методы не возвращают внутренние типы
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: true  # "types" is a valid package name in this project
      - name: error-strings
        severity: error
      - name: error-naming
        severity: error
      - name: error-return
        severity: error
      - name: dot-imports
        severity: error
      - name: unused-parameter
        severity: error  # Ловит _
      - name: import-blacklist
        arguments:
          - internal/cmd
          - internal/adapters/mysql
          - internal/adapters/http
        severity: error
        comment: "Core can only depend on interfaces, not concrete implementations"
      # Limit switch cases indirectly via cyclomatic complexity
      # Note: no direct switch-case-count rule exists - use gocyclo/gocognit
      - name: function-result-limit
        arguments: [3]
        severity: error
      - name: cyclomatic
        arguments: [22]
        severity: error
      - name: cognitive-complexity
        arguments: [25]
        severity: error
      - name: package-level-vars
        severity: error
        comment: "Avoid global state in core packages"
      # Добавьте для лимита аргументов, если нужно
      - name: argument-limit
        arguments: [5]

  nolintlint:
    require-specific: true
    require-explanation: true

  gosec:
    severity: high
    confidence: medium
    excludes:
      - G104


issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - contextcheck
        - funlen
        - gocyclo
        - gocognit

run:
  timeout: 3m
  tests: true
