version: "2"

linters:
  enable:
    # --- Correctness & Safety ---
    - govet
    - staticcheck
    - errcheck
    - bodyclose
    - copyloopvar
    - noctx
    - contextcheck
    - exhaustive
    - gosec

    # --- Code Quality ---
    - unused
    - ineffassign
    - unconvert
    - prealloc
    - errchkjson
    - durationcheck

    # --- Style & Consistency ---
    - revive
    - misspell
    - whitespace
    - tagliatelle
    - gocritic
    - lll

    # --- Complexity & Functions ---
    - gocyclo
    - gocognit
    - funlen
    - maintidx
    - nestif
    - goconst

    # --- Architecture & Discipline ---
    # depguard disabled - not suitable for CLI tools
    - nolintlint

linters-settings:
  funlen:
    lines: 50
    statements: 30
    max-args: 5

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
    enabled-checks:
      - all                 # Включает все доступные проверки

  gocyclo:
    min-complexity: 12

  gocognit:
    min-complexity: 12

  nestif:
    min-complexity: 3

  goconst:
    min-len: 2
    min-occurrences: 2

  maintidx:
    under: 20

  lll:
    # Максимальная длина строки
    line-length: 120
    # Пропускать строки с тегами
    tab-width: 2

  revive:
    rules:
      # NOTE: file-length-limit is configured separately via .revive.toml
      # and run as a standalone check in the lint target (see Makefile)
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: false
      - name: error-strings
        severity: error
      - name: error-naming
        severity: error
      - name: error-return
        severity: error
      - name: dot-imports
        severity: error
      - name: import-blacklist
        arguments:
          - internal/cmd
          - internal/adapters/mysql
          - internal/adapters/http
        severity: error
        comment: "Core can only depend on interfaces, not concrete implementations"
      - name: switch-case-count
        arguments:
          max: 3
          comment: "TODO: consider map+func or strategy pattern for many cases"
      - name: package-level-vars
        severity: error
        comment: "Avoid global state in core packages"
      # Добавьте для лимита аргументов, если нужно
      - name: argument-limit
        arguments: [5]

  nolintlint:
    require-specific: true
    require-explanation: true

  gosec:
    severity: high
    confidence: medium
    excludes:
      - G104


issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - contextcheck
        - funlen
        - gocyclo
        - gocognit

run:
  timeout: 3m
  tests: true
