version: 2

project_name: agent-telegram

before:
  hooks:
    - go mod tidy

builds:
  - id: agent-telegram
    main: .
    binary: agent-telegram
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: user  # Change to your GitHub username
    name: agent-telegram
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

# Publish raw binaries (without archive) for npm postinstall
blobs:
  - provider: gs
    bucket: "{{ .Env.BUCKET }}"
    disable: true  # Enable if you want cloud storage

# Upload extra files to release
extra_files: []
