// Package docs generates CLI documentation from the Cobra command tree.
package docs

import (
	"bytes"
	"cmp"
	"fmt"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"agent-telegram/internal/cliutil"
	"agent-telegram/internal/operations"
)

const (
	commandsBlock      = "commands"
	globalOptionsBlock = "global-options"
)

var groupTitles = map[string]string{
	"server":  "Server Commands",
	"auth":    "Authentication Commands",
	"message": "Message Commands",
	"chat":    "Chat Commands",
	"get":     "Get Commands",
	"other":   "Other Commands",
}

var groupOrder = []string{"server", "auth", "message", "chat", "get", "other"}

// GenerateLLMMarkdown returns full CLI documentation for LLM/tool consumers.
func GenerateLLMMarkdown(rootCmd *cobra.Command) string {
	var b strings.Builder
	writeLLMDocumentation(&b, rootCmd)
	return b.String()
}

// UpdateReadme replaces generated README blocks with content derived from rootCmd.
func UpdateReadme(rootCmd *cobra.Command, src []byte) ([]byte, error) {
	out, err := replaceGeneratedBlock(src, commandsBlock, GenerateReadmeCommands(rootCmd))
	if err != nil {
		return nil, err
	}
	out, err = replaceGeneratedBlock(out, globalOptionsBlock, GenerateReadmeGlobalOptions(rootCmd))
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerateReadmeCommands returns the generated README command reference block.
func GenerateReadmeCommands(rootCmd *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- This section is generated by `agent-telegram docs generate`; do not edit by hand. -->\n\n")
	b.WriteString("Run `agent-telegram --help`, `agent-telegram <command> --help`, or `agent-telegram manifest` for the full command catalog.\n\n")
	b.WriteString("| Area | Commands |\n")
	b.WriteString("|------|----------|\n")

	groups := topLevelGroups(rootCmd)
	for _, groupID := range orderedGroupIDs(groups) {
		cmds := groups[groupID]
		if len(cmds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "| %s | %s |\n",
			escapeMarkdown(groupTitle(groupID)),
			formatCommandNames(cmds),
		)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// GenerateReadmeGlobalOptions returns the generated README global options block.
func GenerateReadmeGlobalOptions(rootCmd *cobra.Command) string {
	var b strings.Builder
	b.WriteString("<!-- This section is generated by `agent-telegram docs generate`; do not edit by hand. -->\n\n")
	b.WriteString("| Option | Description |\n")
	b.WriteString("|--------|-------------|\n")
	rootCmd.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		fmt.Fprintf(&b, "| `%s` | %s |\n", escapeMarkdown(flagUsage(f)), escapeMarkdown(flagDescription(f)))
	})
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeLLMDocumentation(b *strings.Builder, rootCmd *cobra.Command) {
	b.WriteString("# agent-telegram CLI Documentation\n\n")
	b.WriteString("Telegram IPC agent CLI - A command-line tool for interacting with Telegram via IPC server.\n\n")
	b.WriteString("## Agentic Tool Contract\n\n")
	b.WriteString("- Authentication is headless: prefer `auth web --qr` for QR login or `AGENT_TELEGRAM_PHONE=... auth web` for a local one-time code form. Use `auth begin`, `auth verify --code-stdin`, and `auth password --password-stdin` for pure terminal flows.\n")
	b.WriteString("- Auth secrets must be supplied through stdin flags, never as command arguments.\n")
	b.WriteString("- Use `agent-telegram <command> --schema` to inspect input/output schemas, safety, idempotency, and retry hints.\n")
	b.WriteString("- Use `agent-telegram manifest` to inspect the full machine-readable tool catalog without starting HTTP.\n")
	b.WriteString("- Use `agent-telegram skills list` to discover bundled installable skills, and `agent-telegram skills install agent-telegram` to install the Codex skill for this CLI.\n")
	b.WriteString("- Use `agent-telegram serve-api --secret <token>` then `GET /manifest` for a machine-readable tool manifest.\n")
	b.WriteString("- Use `GET /openapi.json` for an OpenAPI 3.1 document.\n")
	b.WriteString("- Use `POST /rpc/{method}?dryRun=true` or body `{ \"dryRun\": true, \"params\": {...} }` to validate without executing.\n")
	b.WriteString("- Prefer `--agent` for automation; it enables compact JSON receipts, run IDs, and structured error envelopes with diagnosis/nextActions.\n")
	b.WriteString("- Use `--run-id ...` or `AGENT_TELEGRAM_RUN_ID` to correlate multiple commands in one agent task.\n")
	b.WriteString("- Use `--verbosity minimal|compact|full|raw`, `--max-items`, `--max-text-chars`, `--summary`, `--include`, and `--omit` to control token usage.\n")
	b.WriteString("- Use `--receipt` to wrap JSON output with trace/action metadata.\n")
	b.WriteString("- Use `audit --trace-id ...`, `audit --run-id ...`, `trace inspect ...`, and `run inspect ...` to analyze recent actions. Audit/log output defaults to `--redaction safe`; `full` redaction mode is intentionally not exposed.\n")
	b.WriteString("- Use `server ensure` before RPC-backed commands; commands do not auto-start the daemon implicitly.\n")
	b.WriteString("- Use `bot step`, `bot press`, and `msg wait` for bot flows; bot state includes structured `nextActions`.\n")
	b.WriteString("- Check `safety`: read, write, destructive, or paid. Destructive and paid operations should be confirmed by the caller.\n")
	b.WriteString("- Check typed error `data.type` for retry decisions, especially `FLOOD_WAIT`, `TIMEOUT`, and `NOT_INITIALIZED`.\n\n")
	fmt.Fprintf(b, "Registered operations: %d\n\n", len(operations.Methods()))
	b.WriteString("## Global Flags\n\n")
	writeFlags(b, rootCmd.PersistentFlags(), "")
	b.WriteString("\n---\n\n## Commands\n\n")

	groups := topLevelGroups(rootCmd)
	for _, groupID := range groupOrder {
		cmds := groups[groupID]
		if len(cmds) == 0 {
			continue
		}
		fmt.Fprintf(b, "### %s\n\n", groupTitle(groupID))
		for _, cmd := range cmds {
			writeCommandDoc(b, cmd, 0)
		}
	}
}

func writeCommandDoc(b *strings.Builder, cmd *cobra.Command, depth int) {
	indent := strings.Repeat("  ", depth)
	headerLevel := strings.Repeat("#", 4+depth)
	if depth > 2 {
		headerLevel = "######"
	}

	fmt.Fprintf(b, "%s%s `%s`\n\n", indent, headerLevel, cmd.CommandPath())
	if cmd.Short != "" {
		fmt.Fprintf(b, "%s%s\n\n", indent, cmd.Short)
	}
	if cmd.Long != "" && cmd.Long != cmd.Short {
		fmt.Fprintf(b, "%s**Description:**\n\n", indent)
		for _, line := range strings.Split(cmd.Long, "\n") {
			fmt.Fprintf(b, "%s%s\n", indent, line)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(b, "%s**Usage:**\n\n", indent)
	fmt.Fprintf(b, "%s```\n%s%s\n%s```\n\n", indent, indent, cmd.UseLine(), indent)
	if len(cmd.Aliases) > 0 {
		fmt.Fprintf(b, "%s**Aliases:** %s\n\n", indent, strings.Join(cmd.Aliases, ", "))
	}
	if argsDesc := argsDescription(cmd); argsDesc != "" {
		fmt.Fprintf(b, "%s**Arguments:** %s\n\n", indent, argsDesc)
	}
	if method, safety := commandMethodSafety(cmd); method != "" {
		fmt.Fprintf(b, "%s**Operation:** `%s` (safety: `%s`)\n\n", indent, method, safety)
	}
	if flags := cmd.Flags(); flags.HasFlags() {
		fmt.Fprintf(b, "%s**Flags:**\n\n", indent)
		writeFlags(b, flags, indent)
		b.WriteString("\n")
	}
	if cmd.Example != "" {
		fmt.Fprintf(b, "%s**Example:**\n\n", indent)
		fmt.Fprintf(b, "%s```\n", indent)
		for _, line := range strings.Split(cmd.Example, "\n") {
			fmt.Fprintf(b, "%s%s\n", indent, line)
		}
		fmt.Fprintf(b, "%s```\n\n", indent)
	}
	fmt.Fprintf(b, "%s---\n\n", indent)

	for _, subcmd := range sortedCommands(cmd.Commands()) {
		if includeCommand(subcmd) {
			writeCommandDoc(b, subcmd, depth+1)
		}
	}
}

func writeFlags(b *strings.Builder, flags *pflag.FlagSet, indent string) {
	flags.VisitAll(func(f *pflag.Flag) {
		fmt.Fprintf(b, "%s- `%s`", indent, flagUsage(f))
		if def := flagDefault(f); def != "" {
			b.WriteString(def)
		}
		b.WriteString("\n")
		if f.Usage != "" {
			fmt.Fprintf(b, "%s  %s\n", indent, f.Usage)
		}
	})
}

func topLevelGroups(rootCmd *cobra.Command) map[string][]*cobra.Command {
	groups := make(map[string][]*cobra.Command)
	for _, cmd := range sortedCommands(rootCmd.Commands()) {
		if !includeCommand(cmd) {
			continue
		}
		groupID := cmd.GroupID
		if groupID == "" {
			groupID = "other"
		}
		groups[groupID] = append(groups[groupID], cmd)
	}
	return groups
}

func orderedGroupIDs(groups map[string][]*cobra.Command) []string {
	out := make([]string, 0, len(groups))
	seen := make(map[string]bool, len(groups))
	for _, groupID := range groupOrder {
		if len(groups[groupID]) == 0 {
			continue
		}
		out = append(out, groupID)
		seen[groupID] = true
	}

	var extras []string
	for groupID := range groups {
		if !seen[groupID] {
			extras = append(extras, groupID)
		}
	}
	slices.Sort(extras)
	return append(out, extras...)
}

func formatCommandNames(cmds []*cobra.Command) string {
	names := make([]string, 0, len(cmds))
	for _, cmd := range cmds {
		names = append(names, "`"+escapeMarkdown(cmd.Name())+"`")
	}
	return strings.Join(names, ", ")
}

func sortedCommands(cmds []*cobra.Command) []*cobra.Command {
	out := slices.Clone(cmds)
	slices.SortStableFunc(out, func(a, b *cobra.Command) int {
		return cmp.Compare(a.Name(), b.Name())
	})
	return out
}

func includeCommand(cmd *cobra.Command) bool {
	return cmd != nil && cmd.IsAvailableCommand() && !cmd.IsAdditionalHelpTopicCommand()
}

func groupTitle(groupID string) string {
	if title, ok := groupTitles[groupID]; ok {
		return title
	}
	return titleCase(groupID) + " Commands"
}

func commandMethodSafety(cmd *cobra.Command) (string, string) {
	method, ok := cliutil.MethodForCommand(cmd)
	if !ok {
		return "", ""
	}
	op, ok := operations.Get(method)
	if !ok {
		return method, ""
	}
	return method, op.Safety
}

func argsDescription(cmd *cobra.Command) string {
	if idx := strings.Index(cmd.Use, " "); idx != -1 {
		args := strings.TrimSpace(cmd.Use[idx+1:])
		if args != "" {
			return "`" + args + "`"
		}
	}
	return ""
}

func flagUsage(f *pflag.Flag) string {
	name := "--" + f.Name
	if f.Shorthand != "" {
		name = "-" + f.Shorthand + ", " + name
	}
	if typ := flagType(f); typ != "" {
		name += " <" + typ + ">"
	}
	return name
}

func flagType(f *pflag.Flag) string {
	switch f.Value.Type() {
	case "bool":
		return ""
	case "stringSlice":
		return "strings"
	default:
		return f.Value.Type()
	}
}

func flagDescription(f *pflag.Flag) string {
	desc := f.Usage
	if def := flagDefault(f); def != "" {
		desc += def
	}
	return strings.TrimSpace(desc)
}

func flagDefault(f *pflag.Flag) string {
	defaultVal := f.DefValue
	if defaultVal == "" || defaultVal == "false" || defaultVal == "0" || defaultVal == "[]" {
		return ""
	}
	return fmt.Sprintf(" (default: %s)", defaultVal)
}

func escapeMarkdown(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.TrimSpace(value)
}

func titleCase(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func replaceGeneratedBlock(src []byte, name, body string) ([]byte, error) {
	begin := []byte("<!-- BEGIN GENERATED:" + name + " -->")
	end := []byte("<!-- END GENERATED:" + name + " -->")
	start := bytes.Index(src, begin)
	if start < 0 {
		return nil, fmt.Errorf("missing generated block start marker for %q", name)
	}
	stop := bytes.Index(src[start:], end)
	if stop < 0 {
		return nil, fmt.Errorf("missing generated block end marker for %q", name)
	}
	stop += start

	var out bytes.Buffer
	out.Write(src[:start+len(begin)])
	out.WriteString("\n")
	out.WriteString(strings.TrimRight(body, "\n"))
	out.WriteString("\n")
	out.Write(src[stop:])
	return out.Bytes(), nil
}
