import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
  type ToolcraftPerformanceScenario,
} from "@/toolcraft/runtime";

const responsiveControl = (
  id: string,
  label: string,
  target: string,
): ToolcraftPerformanceScenario => ({
  automated: true,
  automatedTestName: `perf: ${id} updates within budget`,
  browser: true,
  browserTestName: `browser perf: ${id} updates within budget`,
  budget: { maxFrameGapMs: 80, maxInteractionMs: 500 },
  controlLabel: label,
  expectedObservable: `${label} updates the Duck Agent Card without freezing input or moving the viewport.`,
  fixture: "Default img.jpg at 1920x1080",
  id,
  interaction: "control-change",
  target,
  workload: false,
});

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: ["source-decode", "composition", "export-composite"],
        targets: ["source.image"],
      },
      {
        interaction: "control-drag",
        invalidates: ["composition", "export-composite"],
        mustNotInvalidate: ["source-decode", "text-layout"],
        targets: ["source.scale"],
      },
      {
        interaction: "control-change",
        invalidates: ["text-layout", "composition", "export-composite"],
        mustNotInvalidate: ["source-decode"],
        targets: [
          "card.variant",
          "copy.headline",
          "copy.caption",
          "copy.handle",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "viewport-drag",
        invalidates: ["composition"],
        mustNotInvalidate: ["source-decode", "text-layout"],
        targets: ["canvas.viewport.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: ["composition"],
        mustNotInvalidate: ["source-decode", "text-layout"],
        targets: ["canvas.viewport.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["export-composite"],
        mustNotInvalidate: ["text-layout"],
        targets: ["actions.output", "export.image.resolution"],
      },
    ],
    passes: [
      {
        cacheKey: ["mediaAssets.source.image", "mediaAssets.transform"],
        id: "source-decode",
        inputs: ["mediaAssets.source.image", "mediaAssets.transform"],
        invalidatedBy: ["source.image", "media.transform"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "card.variant",
          "copy.headline",
          "copy.caption",
          "copy.handle",
          "canvas.size",
        ],
        id: "text-layout",
        inputs: ["card.variant", "copy.headline", "copy.caption", "copy.handle", "canvas.size"],
        invalidatedBy: ["card.variant", "copy.*", "canvas.size"],
        kind: "text-layout",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["product.values", "mediaAssets.source.image", "canvas.size"],
        id: "composition",
        inputs: ["source-decode", "text-layout", "product.values", "canvas.viewport"],
        invalidatedBy: ["product.values", "mediaAssets", "canvas.size", "canvas.viewport"],
        kind: "composite",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        id: "export-composite",
        inputs: ["source-decode", "text-layout", "product.values", "canvas.size", "export.image.resolution"],
        invalidatedBy: ["actions.output", "product.values", "mediaAssets", "canvas.size"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "dom",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Canvas export line wrapping must stay visually close to native DOM preview wrapping.",
      "The source image crop and runtime rotate/flip metadata must match preview and export.",
    ],
    layers: [
      {
        content: ["geometry"],
        exportMode: "included",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: '[data-renderer-layer="backgroundLayer"]',
      },
      {
        content: ["bitmap-media", "geometry", "text"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: '[data-renderer-layer="productForegroundLayer"]',
      },
      {
        content: ["bitmap-media", "composite", "geometry", "text"],
        exportMode: "composited",
        id: "exportComposite",
        intentionalRasterizationReason:
          "Downloaded PNG/JPG output must be a portable bitmap at the selected 2K, 4K, or 8K dimensions.",
        kind: "export-composite",
        primitiveCount: "low",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "A 4K uploaded source must decode without blocking normal card controls.",
      "8K export allocates a large canvas and must finish inside the export budget.",
    ],
    previewExportDifferenceReason:
      "Preview uses semantic DOM text for clarity while export uses Canvas 2D to create downloadable bitmap bytes at exact dimensions.",
    previewRenderer: "dom",
    productRepresentation: "mixed",
    rendererStrategy: "dom",
    rendererWorkload: "text-output",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "SVG adds no benefit for one bitmap and low-count card geometry.",
      "WebGL/WebGPU would add texture and text-atlas complexity without meaningful workload reduction.",
      "Canvas-only preview would rasterize low-count semantic text unnecessarily.",
    ],
  },
  rendererWorkload: "text-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: initial preview renders within budget",
      browser: true,
      browserTestName: "browser perf: initial preview renders within budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 1200 },
      expectedObservable: "The default Hero card and img.jpg become visible promptly.",
      fixture: "Default img.jpg at 1920x1080",
      id: "initial-preview",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A 4K source is the heaviest realistic preview input.",
        value: { height: 2160, width: 3840 },
      },
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
    responsiveControl("variant-change", "Variant", "card.variant"),
    {
      automated: true,
      automatedTestName: "perf: source image import stays responsive",
      browser: true,
      browserTestName: "browser perf: source image import stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1500 },
      controlLabel: "Photo",
      expectedObservable: "A 4K image imports and replaces the card photo without freezing controls.",
      fixture: "3840x2160 generated image upload",
      id: "source-media-import",
      interaction: "media-import",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the realistic heavy source size for a social promo-card editor.",
        value: { height: 2160, width: 3840 },
      },
      target: "source.image",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: source scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: source scale drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Image scale",
      expectedObservable: "Dragging Image scale updates the live crop without re-decoding img.jpg.",
      fixture: "Default img.jpg at maximum crop scale",
      id: "source-scale-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 140,
          metric: "numeric-max",
          smoothTarget: 140,
          smoothTargetRatio: 1,
          target: "source.scale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "140% is the maximum user-selectable crop scale.",
        value: 140,
      },
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Scale drag must stay smooth with a realistic 4K source already attached.",
        value: { height: 2160, width: 3840 },
      },
      target: "source.scale",
      values: { default: 104, max: 140, min: 80 },
      workload: true,
    },
    responsiveControl("headline-change", "Headline", "copy.headline"),
    responsiveControl("caption-change", "Caption", "copy.caption"),
    responsiveControl("handle-change", "Telegram", "copy.handle"),
    responsiveControl("accent-change", "Accent", "appearance.accent"),
    responsiveControl("include-background-change", "Include", "export.includeBackground"),
    responsiveControl("background-change", "Background", "appearance.background"),
    responsiveControl("format-change", "Format", "export.image.format"),
    {
      automated: true,
      automatedTestName: "perf: export resolution selection stays responsive",
      browser: true,
      browserTestName: "browser perf: export resolution selection stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 500 },
      controlLabel: "Resolution",
      expectedObservable: "Selecting 8K updates export settings without allocating the canvas before export.",
      fixture: "Default card with 2K, 4K, and 8K options",
      id: "resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the maximum export resolution offered by the product.",
        value: "8k",
      },
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Resolution selection is measured with a realistic 4K source already attached.",
        value: { height: 2160, width: 3840 },
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: zoom remains smooth with 4K source",
      browser: true,
      browserTestName: "browser perf: zoom remains smooth with 4K source",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1200, maxLongTaskMs: 200 },
      expectedObservable: "Toolbar zoom remains smooth and does not re-decode the 4K source image.",
      fixture: "Hero card with generated 3840x2160 source",
      id: "viewport-zoom",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K source plus real toolbar zoom is the heaviest viewport interaction.",
        value: { height: 2160, width: 3840 },
      },
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: 8K export completes within budget",
      browser: true,
      browserTestName: "browser perf: 8K export completes within budget",
      budget: { maxExportMs: 8000 },
      controlLabel: "Export image",
      expectedObservable: "The selected 8K card exports valid bytes without locking the editor indefinitely.",
      fixture: "Cards variant with default img.jpg and 8K resolution",
      id: "export-image",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K exercises the largest export canvas exposed in the UI.",
        value: "8k",
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport remains stable while editing",
      browser: true,
      browserTestName: "browser perf: viewport remains stable while editing",
      budget: { maxFrameGapMs: 80 },
      expectedObservable: "Canvas offset, zoom, and output dimensions remain stable during card edits.",
      fixture: "Default img.jpg with Hero and Chat variants",
      id: "viewport-stability",
      interaction: "viewport-stability",
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: ["source.scale", "export.image.resolution"],
});
